name: Test and Deploy

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm test
      env:
        NODE_ENV: test
        CLIENT_ID: 'fake-microsoft-client-id-for-testing'
        CLIENT_SECRET: 'fake-microsoft-secret-for-testing'
        GOOGLE_CLIENT_ID: 'fake-google-client-id-for-testing'
        GOOGLE_CLIENT_SECRET: 'fake-google-secret-for-testing'
        SESSION_SECRET: 'fake-session-secret-for-github-actions-testing'
        BASE_URL: 'http://localhost:3000'
        PORT: '3001'

    - name: Run test coverage
      run: npm run test:coverage
      env:
        NODE_ENV: test
        CLIENT_ID: 'fake-microsoft-client-id-for-testing'
        CLIENT_SECRET: 'fake-microsoft-secret-for-testing'
        GOOGLE_CLIENT_ID: 'fake-google-client-id-for-testing'
        GOOGLE_CLIENT_SECRET: 'fake-google-secret-for-testing'
        SESSION_SECRET: 'fake-session-secret-for-github-actions-testing'
        BASE_URL: 'http://localhost:3000'

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Deploy to Railway
      run: npx @railway/cli@latest deploy --detach
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}